name: GitHub Metrics

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General Stats + Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: TChehab
          template: classic
          base: header, activity, community
          config_timezone: America/Sao_Paulo
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Languages Pie Chart
        uses: lowlighter/metrics@latest
        with:
          filename: assets/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: TChehab
          base: ""
          plugin_languages: yes
          plugin_languages_count: 10
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_threshold: 0%
          config_timezone: America/Sao_Paulo
